config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :retails
  root to: 'retails#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  


  
end

app/models/retail.rb
class Retail < ActiveRecord::Base

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:eventName, :eventPlan, :eventAppearance, :eventAlcohol)
    end
end

app/controllers/retails_controller.rb
class RetailsController < ApplicationController
  before_action :set_retail, only: [:show, :edit, :update, :destroy]

  # GET /retails
  # GET /retails.json
  def index
    @retails = Retail.all
  end

  # GET /retails/1
  # GET /retails/1.json
  def show

  end

  # GET /retails/new
  def new
    @retail = Retail.new
  end

  # GET /retails/1/edit
  def edit
  end

  # POST /retails
  # POST /retails.json
  def create
    @retail = Retail.new(retail_params)

    respond_to do |format|
      if @retail.save
        format.html { redirect_to @retail, notice: 'Retail was successfully created.' }
        format.json { render :show, status: :created, location: @retail }
      else
        format.html { render :new }
        format.json { render json: @retail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retails/1
  # PATCH/PUT /retails/1.json
  def update
    respond_to do |format|
      if @retail.update(retail_params)
        format.html { redirect_to @retail, notice: 'Retail was successfully updated.' }
        format.json { render :show, status: :ok, location: @retail }
      else
        format.html { render :edit }
        format.json { render json: @retail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retails/1
  # DELETE /retails/1.json
  def destroy
    @retail.destroy
    respond_to do |format|
      format.html { redirect_to retails_url, notice: 'Retail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retail
      @retail = Retail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def retail_params
      params.require(:retail).permit(:retailName, :retailBrand, :rentailAppearance, :retailSell)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/retails_helper.rb
module RetailsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :eventName
    = f.text_field :eventName
  .field
    = f.label :eventPlan
    = f.text_area :eventPlan
  .field
    = f.label :eventAppearance
    = f.check_box :eventAppearance
  .field
    = f.label :eventAlcohol
    = f.check_box :eventAlcohol
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %tr
    %th Eventname
    %th Eventplan
    %th Eventappearance
    %th Eventalcohol
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= event.eventName
      %td= event.eventPlan
      %td= event.eventAppearance
      %td= event.eventAlcohol
      %td= link_to 'Show', event
      %td= link_to 'Edit', edit_event_path(event)
      %td= link_to 'Destroy', event, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Eventname:
  = @event.eventName
%p
  %b Eventplan:
  = @event.eventPlan
%p
  %b Eventappearance:
  = @event.eventAppearance
%p
  %b Eventalcohol:
  = @event.eventAlcohol

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %nav.top-bar{"data-topbar" => "", :role => "navigation"}
      %ul.title-area
        %li.name
          %h1
            %a{:href => "#"} Appear [ here ]
        / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
        %li.toggle-topbar.menu-icon
          %a{:href => "#"}
            %span Menu
      %section.top-bar-section
        / Right Nav Section
        %ul.right
          %li.active
            %a{:href => "#"} Right Button Active
          %li.has-dropdown
            %a{:href => "#"} Right Button Dropdown
            %ul.dropdown
              %li
                %a{:href => "#"} First link in dropdown
              %li.active
                %a{:href => "#"} Active link in dropdown
        / Left Nav Section
        %ul.left
          %li
            %a#getRetails SAVED RENTALS
          %li
            %a#getEvents SAVED EVENTS
          %li
            %a{:href => "#"} MAGAZINE  
    = yield
    = javascript_include_tag "application"

app/views/retails/_form.html.haml
= form_for @retail do |f|
  - if @retail.errors.any?
    #error_explanation
      %h2= "#{pluralize(@retail.errors.count, "error")} prohibited this retail from being saved:"
      %ul
        - @retail.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :retailName
    = f.text_field :retailName
  .field
    = f.label :retailBrand
    = f.text_field :retailBrand
  .field
    = f.label :rentailAppearance
    = f.text_field :rentailAppearance
  .field
    = f.label :retailSell
    = f.text_field :retailSell
  .actions
    = f.submit 'Save'

app/views/retails/edit.html.haml
%h1 Editing retail

= render 'form'

= link_to 'Show', @retail
\|
= link_to 'Back', retails_path

app/views/retails/index.html.haml
.inner
  .row
    .large-12columns
      .mainContainer
        %header
          %h1 Pitch Us your idea
          %p This goes straight to the landlord to give it your best
    .content-container    
      .row        
        #introduction 
          %h3 What will you use this space for?
          .large-6.columns
            .boxcontainer#showRetail 
              %br/
              %i.fa.fa-home.fa-3x
              %br/
              %a Retail
          .large-6.columns
            .boxcontainer#showEvents
              %br/
              %i.fa.fa-ticket.fa-3x
              %br/
              %a Events      

                
      .row
        .large-12.columns
          #main-content    
            #new_retail{:style => "display: none"}
              = form_tag "", id: "retail_form" do |f|
                .field
                  %h3 What would you call your store? 
                  %p#greytext Give your idea a name to save it, you can always change this later
                  %br/
                  = text_field_tag :retailStore
                  %br/
                  %br/
                .field
                  %h3 Describe your brand
                  %br/
                  
                  = text_field_tag :retailBrand
                .field
                  %h3 How will the space look?
                  .large-4.columns.apperanceContainer
                    %img#appearOne{:src => "/assets/clear.png"}/
                    .apperanceDescriptionContainer
                      %p WhiteBox
                      = radio_button_tag :rentailAppearance , 'emptyyyy'
                  .large-4.columns.apperanceContainer
                    %img#appearTwo{:src => "/assets/light.png", style: "width:250px; height:200px"}/
                    .apperanceDescriptionContainer
                      %p Lightly Decorated
                      = radio_button_tag :rentailAppearance , 'half'
                  .large-4.columns.apperanceContainer 
                    %img#appearThree{:src => "/assets/heavy.png", style: "width:250px; height:200px"}/
                    .apperanceDescriptionContainer
                      %p Heavily Decorated
                      = radio_button_tag :rentailAppearance , 'full'
                  / = text_field_tag :rentailAppearance
                  %br/ 
                  %br/
                  %br/
                .field
                  %h3 What would you sell? 
                  %p#greytext Submit links to your products or services online
                  %br/
                  = text_field_tag :retailSell
                .retailactions
                  = submit_tag
            #new_event{:style => "display: none"}
              = form_tag "", id: "event_form" do |f|
                .field
                  %h3 What will you call your event?
                  %p#greytext Give your idea a name to save it, you can always change this later
                  = text_field_tag :eventName
                .field
                  %h3 Event Plan
                  %p#greytext Tell us about what will happen in this event
                  = text_area_tag :eventPlan
                .field
                  %h3 What will the event look like?
                  .large-4.columns.apperanceContainer
                    %img#appearEventOne{:src => "/assets/clear.png"}/
                    .apperanceDescriptionContainer
                      %p WhiteBox
                      = radio_button_tag :eventAppearance , 'empty'
                  .large-4.columns.apperanceContainer
                    %img#appearEventTwo{:src => "/assets/light.png"}/
                    .apperanceDescriptionContainer
                      %p Lightly Decorated
                      = radio_button_tag :eventAppearance , 'half'
                  .large-4.columns.apperanceContainer 
                    %img#appearEventThree{:src => "/assets/heavy.png"}/
                    .apperanceDescriptionContainer
                      %p Heavily Decorated
                      = radio_button_tag :eventAppearance , 'full'
                .field
                  %h3 Will you be serving Alcohol?
                  = check_box_tag :eventAlcohol
                .actions
                  = submit_tag


          #all_retails{:style => "display: none"}     
            %table
              %thead
                %tr
                  %th Retailstore
                  %th Retailbrand
                  %th Retailapperance
                  %th RetailSell
                  / %th Retailsell
                  / %th Eventspace
                  / %th Eventstore
                  / %th Eventbrand
                  / %th Eventapperance
                  / %th Eventalcohol
                  / %th{:colspan => "3"}
              %tbody 
          #all_events{:style => "display: none"} 
            %table
              %thead
                %tr
                  %th EventName
                  %th EventPlan
                  %th EventApperance
                  %th EventAlchol
                  / %th Retailsell
                  / %th Eventspace
                  / %th Eventstore
                  / %th Eventbrand
                  / %th Eventapperance
                  / %th Eventalcohol
                  / %th{:colspan => "3"}
              %tbody                

= link_to 'New Retail', new_retail_path

app/views/retails/new.html.haml
%h1 New retail

= render 'form'

= link_to 'Back', retails_path

app/views/retails/show.html.haml
%p#notice= notice

%p
  %b Retailname:
  = @retail.retailName
%p
  %b Retailbrand:
  = @retail.retailBrand
%p
  %b Rentailappearance:
  = @retail.rentailAppearance
%p
  %b Retailsell:
  = @retail.retailSell

= link_to 'Edit', edit_retail_path(@retail)
\|
= link_to 'Back', retails_path